In [1]:
import pandas as pd
import matplotlib.pyplot as plot
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\Otpat\Downloads\titanic_data.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
df['Age'] = df['Age'].apply(lambda x: str(x))
df['Age'] = df['Age'].str.replace('nan', '')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df['Cabin'] = df['Cabin'].apply(lambda x: str(x))
df['Cabin'] = df['Cabin'].str.replace('nan', '')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,,1,2,W./C. 6607,23.4500,,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,,Q

In [6]:
df['Embarked'] = df['Embarked'].apply(lambda x: str(x))
df['Embarked'] = df['Embarked'].str.replace('nan', '')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,,1,2,W./C. 6607,23.4500,,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,,Q

In [7]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [8]:
df['Name'] = df['Name'].str.replace(r'\(.*?\)', '', regex=True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,,S
1,2,1,1,"Cumings, Mrs. John Bradley",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,,1,2,W./C. 6607,23.4500,,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,,Q

In [9]:
df['Name'] = df['Name'].str.replace(r'"[^"]*"', '', regex=True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,,S
1,2,1,1,"Cumings, Mrs. John Bradley",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen",female,,1,2,W./C. 6607,23.4500,,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,,Q

In [10]:
# Function to move text after the comma to the front
def name_reposition(text):
    if ',' in text:  # Check if the string contains a comma
        parts = text.split(',', 1)  # Split the string into two parts at the first comma
        return parts[1].strip() + ' ' + parts[0].strip()  # Move text after comma to the front
    return text  # Return unchanged if no comma is present

# Apply the function to the 'Name' column
df['Name'] = df['Name'].apply(name_reposition)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Mr. Owen Harris Braund,male,22.0,1,0,A/5 21171,7.2500,,S
1,2,1,1,Mrs. John Bradley Cumings,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,Miss. Laina Heikkinen,female,26.0,0,0,STON/O2. 3101282,7.9250,,S
3,4,1,1,Mrs. Jacques Heath Futrelle,female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,Mr. William Henry Allen,male,35.0,0,0,373450,8.0500,,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,Rev. Juozas Montvila,male,27.0,0,0,211536,13.0000,,S
887,888,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,Miss. Catherine Helen Johnston,female,,1,2,W./C. 6607,23.4500,,S
889,890,1,1,Mr. Karl Howell Behr,male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,Mr. Patrick Dooley,male,32.0,0,0,370376,7.7500,,Q

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    object
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 83.7+ KB

In [14]:
df['Ticket'].value_counts()

Ticket
347082      7
CA. 2343    7
1601        7
3101295     6
CA 2144     6
           ..
9234        1
19988       1
2693        1
PC 17612    1
370376      1
Name: count, Length: 681, dtype: int64

In [15]:
df[df['Ticket']=='347082']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
13,14,0,3,Mr. Anders Johan Andersson,male,39.0,1,5,347082,31.275,,S
119,120,0,3,Miss. Ellis Anna Maria Andersson,female,2.0,4,2,347082,31.275,,S
541,542,0,3,Miss. Ingeborg Constanzia Andersson,female,9.0,4,2,347082,31.275,,S
542,543,0,3,Miss. Sigrid Elisabeth Andersson,female,11.0,4,2,347082,31.275,,S
610,611,0,3,Mrs. Anders Johan Andersson,female,39.0,1,5,347082,31.275,,S
813,814,0,3,Miss. Ebba Iris Alfrida Andersson,female,6.0,4,2,347082,31.275,,S
850,851,0,3,Master. Sigvard Harald Elias Andersson,male,4.0,4,2,347082,31.275,,S

In [97]:
df['Ticket'] = df['Ticket'].drop_duplicates()
df[df['Ticket']=='347082']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
13,14,0,3,Mr. Anders Johan Andersson,male,39.0,1,5,347082,31.275,,S

In [135]:
df['Ticket'].value_counts()

Ticket
             210
A/5 21171      1
2620           1
13568          1
WE/P 5735      1
            ...
PC 17585       1
110152         1
PC 17755       1
230433         1
370376         1
Name: count, Length: 682, dtype: int64

In [111]:
df['Ticket'] = df['Ticket'].fillna('')

In [113]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Mr. Owen Harris Braund,male,22.0,1,0,A/5 21171,7.2500,,S
1,2,1,1,Mrs. John Bradley Cumings,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,Miss. Laina Heikkinen,female,26.0,0,0,STON/O2. 3101282,7.9250,,S
3,4,1,1,Mrs. Jacques Heath Futrelle,female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,Mr. William Henry Allen,male,35.0,0,0,373450,8.0500,,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,Rev. Juozas Montvila,male,27.0,0,0,211536,13.0000,,S
887,888,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,Miss. Catherine Helen Johnston,female,,1,2,,23.4500,,S
889,890,1,1,Mr. Karl Howell Behr,male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,Mr. Patrick Dooley,male,32.0,0,0,370376,7.7500,,Q

In [181]:
df['Sex'] = df['Sex'].replace({'female':'Female', 'male':'Male'})

In [173]:
df.head(50)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,Mr. Owen Harris Braund,Male,22.0,1,0,A/5 21171,7.2500,,S
2,1,1,Mrs. John Bradley Cumings,feMale,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,Miss. Laina Heikkinen,feMale,26.0,0,0,STON/O2. 3101282,7.9250,,S
4,1,1,Mrs. Jacques Heath Futrelle,feMale,35.0,1,0,113803,53.1000,C123,S
5,0,3,Mr. William Henry Allen,Male,35.0,0,0,373450,8.0500,,S
6,0,3,Mr. James Moran,Male,,0,0,330877,8.4583,,Q
7,0,1,Mr. Timothy J McCarthy,Male,54.0,0,0,17463,51.8625,E46,S
8,0,3,Master. Gosta Leonard Palsson,Male,2.0,3,1,349909,21.0750,,S
9,1,3,Mrs. Oscar W Johnson,feMale,27.0,0,2,347742,11.1333,,S
10,1,2,Mrs. Nicholas Nasser,feMale,14.0,1,0,237736,30.0708,,C
11,1,3,Miss. Marguerite Rut Sandstrom,feMale,4.0,1,1,PP 9549,16.7000,G6,S
12,1,1,Miss. Elizabeth Bonnell,feMale,58.0,0,0,113783,26.5500,C103,S
13,0,3,Mr. William Henry Saundercock,Male,20.0,0,0,A/5. 2151,8.0500,,S
14,0,3,Mr. Anders Johan Andersson,Male,39.0,1,5,347082,31.2750,,S
15,0,3,Miss. Hulda Amanda Adolfina Vestrom,feMale,14.0,0,0,350406,7.8542,,S
16,1,2,Mrs. Hewlett,feMale,55.0,0,0,248706,16.0000,,S
17,0,3,Master. Eugene Rice,Male,2.0,4,1,382652,29.1250,,Q
18,1,2,Mr. Charles Eugene Williams,Male,,0,0,244373,13.0000,,S
19,0,3,Mrs. Julius Vander Planke,feMale,31.0,1,0,345763,18.0000,,S
20,1,3,Mrs. Fatima Masselmani,feMale,,0,0,2649,7.2250,,C
21,0,2,Mr. Joseph J Fynney,Male,35.0,0,0,239865,26.0000,,S
22,1,2,Mr. Lawrence Beesley,Male,34.0,0,0,248698,13.0000,D56,S
23,1,3,Miss. Anna McGowan,feMale,15.0,0,0,330923,8.0292,,Q
24,1,1,Mr. William Thompson Sloper,Male,28.0,0,0,113788,35.5000,A6,S
25,0,3,Miss. Torborg Danira Palsson,feMale,8.0,3,1,,21.0750,,S
26,1,3,Mrs. Carl Oscar Asplund,feMale,38.0,1,5,347077,31.3875,,S
27,0,3,Mr. Farred Chehab Emir,Male,,0,0,2631,7.2250,,C
28,0,1,Mr. Charles Alexander Fortune,Male,19.0,3,2,19950,263.0000,C23 C25 C27,S
29,1,3,Miss. Ellen O'Dwyer,feMale,,0,0,330959,7.8792,,Q
30,0,3,Mr. Lalio Todoroff,Male,,0,0,349216,7.8958,,S
31,0,1,Don. Manuel E Uruchurtu,Male,40.0,0,0,PC 17601,27.7208,,C
32,1,1,Mrs. William Augustus Spencer,feMale,,1,0,PC 17569,146.5208,B78,C
33,1,3,Miss. Mary Agatha Glynn,feMale,,0,0,335677,7.7500,,Q
34,0,2,Mr. Edward H Wheadon,Male,66.0,0,0,C.A. 24579,10.5000,,S
35,0,1,Mr. Edgar Joseph Meyer,Male,28.0,1,0,PC 17604,82.1708,,C
36,0,1,Mr. Alexander Oskar Holverson,Male,42.0,1,0,113789,52.0000,,S
37,1,3,Mr. Hanna Mamee,Male,,0,0,2677,7.2292,,C
38,0,3,Mr. Ernest Charles Cann,Male,21.0,0,0,A./5. 2152,8.0500,,S
39,0,3,Miss. Augusta Maria Vander Planke,feMale,18.0,2,0,345764,18.0000,,S
40,1,3,Miss. Jamila Nicola-Yarred,feMale,14.0,1,0,2651,11.2417,,C
41,0,3,Mrs. Johan Ahlin,feMale,40.0,1,0,7546,9.4750,,S
42,0,2,Mrs. William John Robert Turpin,feMale,27.0,1,0,11668,21.0000,,S
43,0,3,Mr. Theodor Kraeff,Male,,0,0,349253,7.8958,,C
44,1,2,Miss. Simonne Marie Anne Andree Laroche,feMale,3.0,1,2,SC/Paris 2123,41.5792,,C
45,1,3,Miss. Margaret Delia Devaney,feMale,19.0,0,0,330958,7.8792,,Q
46,0,3,Mr. William John Rogers,Male,,0,0,S.C./A.4. 23567,8.0500,,S
47,0,3,Mr. Denis Lennon,Male,,1,0,370371,15.5000,,Q
48,1,3,Miss. Bridget O'Driscoll,feMale,,0,0,14311,7.7500,,Q
49,0,3,Mr. Youssef Samaan,Male,,2,0,2662,21.6792,,C
50,0,3,Mrs. Josef Arnold-Franchi,feMale,18.0,1,0,349237,17.8000,,S

In [147]:
df.set_index('PassengerId', inplace=True)

In [175]:
df['Sex'] = df['Sex'].replace('feMale', 'Female')
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,Mr. Owen Harris Braund,Male,22.0,1,0,A/5 21171,7.2500,,S
2,1,1,Mrs. John Bradley Cumings,Female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,Miss. Laina Heikkinen,Female,26.0,0,0,STON/O2. 3101282,7.9250,,S
4,1,1,Mrs. Jacques Heath Futrelle,Female,35.0,1,0,113803,53.1000,C123,S
5,0,3,Mr. William Henry Allen,Male,35.0,0,0,373450,8.0500,,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,Rev. Juozas Montvila,Male,27.0,0,0,211536,13.0000,,S
888,1,1,Miss. Margaret Edith Graham,Female,19.0,0,0,112053,30.0000,B42,S
889,0,3,Miss. Catherine Helen Johnston,Female,,1,2,,23.4500,,S
890,1,1,Mr. Karl Howell Behr,Male,26.0,0,0,111369,30.0000,C148,C
891,0,3,Mr. Patrick Dooley,Male,32.0,0,0,370376,7.7500,,Q

In [185]:
for x in df.index:
    if df.loc[x, 'Age'] == '':
        df.drop(x, inplace=True)
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,Mr. Owen Harris Braund,Male,22.0,1,0,A/5 21171,7.2500,,S
2,1,1,Mrs. John Bradley Cumings,Female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,Miss. Laina Heikkinen,Female,26.0,0,0,STON/O2. 3101282,7.9250,,S
4,1,1,Mrs. Jacques Heath Futrelle,Female,35.0,1,0,113803,53.1000,C123,S
5,0,3,Mr. William Henry Allen,Male,35.0,0,0,373450,8.0500,,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,3,Mrs. William Rice,Female,39.0,0,5,,29.1250,,Q
887,0,2,Rev. Juozas Montvila,Male,27.0,0,0,211536,13.0000,,S
888,1,1,Miss. Margaret Edith Graham,Female,19.0,0,0,112053,30.0000,B42,S
890,1,1,Mr. Karl Howell Behr,Male,26.0,0,0,111369,30.0000,C148,C
891,0,3,Mr. Patrick Dooley,Male,32.0,0,0,370376,7.7500,,Q

In [225]:
df.drop(['Ticket', 'SibSp', 'Fare', 'Parch'], axis=1, errors='ignore')
df

,Survived,Pclass,Name,Sex,Age,Cabin,Embarked
PassengerId,,,,,,,
1,0,3,Mr. Owen Harris Braund,Male,22.0,,S
2,1,1,Mrs. John Bradley Cumings,Female,38.0,C85,C
3,1,3,Miss. Laina Heikkinen,Female,26.0,,S
4,1,1,Mrs. Jacques Heath Futrelle,Female,35.0,C123,S
5,0,3,Mr. William Henry Allen,Male,35.0,,S
...,...,...,...,...,...,...,...
886,0,3,Mrs. William Rice,Female,39.0,,Q
887,0,2,Rev. Juozas Montvila,Male,27.0,,S
888,1,1,Miss. Margaret Edith Graham,Female,19.0,B42,S
890,1,1,Mr. Karl Howell Behr,Male,26.0,C148,C
891,0,3,Mr. Patrick Dooley,Male,32.0,,Q

In [239]:
df = df[['Name', 'Sex', 'Age', 'Cabin', 'Pclass', 'Survived', 'Embarked']]
df

,Name,Sex,Age,Cabin,Pclass,Survived,Embarked
PassengerId,,,,,,,
1,Mr. Owen Harris Braund,Male,22.0,,3,0,S
2,Mrs. John Bradley Cumings,Female,38.0,C85,1,1,C
3,Miss. Laina Heikkinen,Female,26.0,,3,1,S
4,Mrs. Jacques Heath Futrelle,Female,35.0,C123,1,1,S
5,Mr. William Henry Allen,Male,35.0,,3,0,S
...,...,...,...,...,...,...,...
886,Mrs. William Rice,Female,39.0,,3,0,Q
887,Rev. Juozas Montvila,Male,27.0,,2,0,S
888,Miss. Margaret Edith Graham,Female,19.0,B42,1,1,S
890,Mr. Karl Howell Behr,Male,26.0,C148,1,1,C
891,Mr. Patrick Dooley,Male,32.0,,3,0,Q

In [245]:
pd.set_option('display.max.rows', 891)

In [247]:
df

,Name,Sex,Age,Cabin,Pclass,Survived,Embarked
PassengerId,,,,,,,
1,Mr. Owen Harris Braund,Male,22.0,,3,0,S
2,Mrs. John Bradley Cumings,Female,38.0,C85,1,1,C
3,Miss. Laina Heikkinen,Female,26.0,,3,1,S
4,Mrs. Jacques Heath Futrelle,Female,35.0,C123,1,1,S
5,Mr. William Henry Allen,Male,35.0,,3,0,S
7,Mr. Timothy J McCarthy,Male,54.0,E46,1,0,S
8,Master. Gosta Leonard Palsson,Male,2.0,,3,0,S
9,Mrs. Oscar W Johnson,Female,27.0,,3,1,S
10,Mrs. Nicholas Nasser,Female,14.0,,2,1,C
11,Miss. Marguerite Rut Sandstrom,Female,4.0,G6,3,1,S
12,Miss. Elizabeth Bonnell,Female,58.0,C103,1,1,S
13,Mr. William Henry Saundercock,Male,20.0,,3,0,S
14,Mr. Anders Johan Andersson,Male,39.0,,3,0,S
15,Miss. Hulda Amanda Adolfina Vestrom,Female,14.0,,3,0,S
16,Mrs. Hewlett,Female,55.0,,2,1,S
17,Master. Eugene Rice,Male,2.0,,3,0,Q
19,Mrs. Julius Vander Planke,Female,31.0,,3,0,S
21,Mr. Joseph J Fynney,Male,35.0,,2,0,S
22,Mr. Lawrence Beesley,Male,34.0,D56,2,1,S
23,Miss. Anna McGowan,Female,15.0,,3,1,Q
24,Mr. William Thompson Sloper,Male,28.0,A6,1,1,S
25,Miss. Torborg Danira Palsson,Female,8.0,,3,0,S
26,Mrs. Carl Oscar Asplund,Female,38.0,,3,1,S
28,Mr. Charles Alexander Fortune,Male,19.0,C23 C25 C27,1,0,S
31,Don. Manuel E Uruchurtu,Male,40.0,,1,0,C
34,Mr. Edward H Wheadon,Male,66.0,,2,0,S
35,Mr. Edgar Joseph Meyer,Male,28.0,,1,0,C
36,Mr. Alexander Oskar Holverson,Male,42.0,,1,0,S
38,Mr. Ernest Charles Cann,Male,21.0,,3,0,S
39,Miss. Augusta Maria Vander Planke,Female,18.0,,3,0,S
40,Miss. Jamila Nicola-Yarred,Female,14.0,,3,1,C
41,Mrs. Johan Ahlin,Female,40.0,,3,0,S
42,Mrs. William John Robert Turpin,Female,27.0,,2,0,S
44,Miss. Simonne Marie Anne Andree Laroche,Female,3.0,,2,1,C
45,Miss. Margaret Delia Devaney,Female,19.0,,3,1,Q
50,Mrs. Josef Arnold-Franchi,Female,18.0,,3,0,S
51,Master. Juha Niilo Panula,Male,7.0,,3,0,S
52,Mr. Richard Cater Nosworthy,Male,21.0,,3,0,S
53,Mrs. Henry Sleeper Harper,Female,49.0,D33,1,1,C
54,Mrs. Lizzie Faunthorpe,Female,29.0,,2,1,S
55,Mr. Engelhart Cornelius Ostby,Male,65.0,B30,1,0,C
57,Miss. Emily Rugg,Female,21.0,,2,1,S
58,Mr. Mansouer Novel,Male,28.5,,3,0,C
59,Miss. Constance Mirium West,Female,5.0,,2,1,S
60,Master. William Frederick Goodwin,Male,11.0,,3,0,S
61,Mr. Orsen Sirayanian,Male,22.0,,3,0,C
62,Miss. Amelie Icard,Female,38.0,B28,1,1,
63,Mr. Henry Birkhardt Harris,Male,45.0,C83,1,0,S
64,Master. Harald Skoog,Male,4.0,,3,0,S
67,Mrs. Nye,Female,29.0,F33,2,1,S
68,Mr. Ernest James Crease,Male,19.0,,3,0,S
69,Miss. Erna Alexandra Andersson,Female,17.0,,3,1,S
70,Mr. Vincenz Kink,Male,26.0,,3,0,S
71,Mr. Stephen Curnow Jenkin,Male,32.0,,2,0,S
72,Miss. Lillian Amy Goodwin,Female,16.0,,3,0,S
73,Mr. Ambrose Jr Hood,Male,21.0,,2,0,S
74,Mr. Apostolos Chronopoulos,Male,26.0,,3,0,C
75,Mr. Lee Bing,Male,32.0,,3,1,S
76,Mr. Sigurd Hansen Moen,Male,25.0,F G73,3,0,S
79,Master. Alden Gates Caldwell,Male,0.83,,2,1,S
80,Miss. Elizabeth Dowdell,Female,30.0,,3,1,S
81,Mr. Achille Waelens,Male,22.0,,3,0,S
82,Mr. Jan Baptist Sheerlinck,Male,29.0,,3,1,S
84,Mr. Francisco M Carrau,Male,28.0,,1,0,S
85,Miss. Bertha Ilett,Female,17.0,,2,1,S
86,Mrs. Karl Alfred Backstrom,Female,33.0,,3,1,S
87,Mr. William Neal Ford,Male,16.0,,3,0,S
89,Miss. Mabel Helen Fortune,Female,23.0,C23 C25 C27,1,1,S
90,Mr. Francesco Celotti,Male,24.0,,3,0,S
91,Mr. Emil Christmann,Male,29.0,,3,0,S
92,Mr. Paul Edvin Andreasson,Male,20.0,,3,0,S
93,Mr. Herbert Fuller Chaffee,Male,46.0,E31,1,0,S
94,Mr. Bertram Frank Dean,Male,26.0,,3,0,S
95,Mr. Daniel Coxon,Male,59.0,,3,0,S
97,Mr. George B Goldschmidt,Male,71.0,A5,1,0,C
98,Mr. William Bertram Greenfield,Male,23.0,D10 D12,1,1,C
99,Mrs. John T Doling,Female,34.0,,2,1,S
100,Mr. Sinai Kantor,Male,34.0,,2,0,S
101,Miss. Matilda Petranec,Female,28.0,,3,0,S
103,Mr. Richard Frasar White,Male,21.0,D26,1,0,S
104,Mr. Gustaf Joel Johansson,Male,33.0,,3,0,S
105,Mr. Anders Vilhelm Gustafsson,Male,37.0,,3,0,S
106,Mr. Stoytcho Mionoff,Male,28.0,,3,0,S
107,Miss. Anna Kristine Salkjelsvik,Female,21.0,,3,1,S
109,Mr. Tido Rekic,Male,38.0,,3,0,S
111,Mr. Walter Chamberlain Porter,Male,47.0,C110,1,0,S
112,Miss. Hileni Zabour,Female,14.5,,3,0,C
113,Mr. David John Barton,Male,22.0,,3,0,S
114,Miss. Katriina Jussila,Female,20.0,,3,0,S
115,Miss. Malake Attalah,Female,17.0,,3,0,C
116,Mr. Edvard Pekoniemi,Male,21.0,,3,0,S
117,Mr. Patrick Connors,Male,70.5,,3,0,Q
118,Mr. William John Robert Turpin,Male,29.0,,2,0,S
119,Mr. Quigg Edmond Baxter,Male,24.0,B58 B60,1,0,C
120,Miss. Ellis Anna Maria Andersson,Female,2.0,,3,0,S
121,Mr. Stanley George Hickman,Male,21.0,,2,0,S
123,Mr. Nicholas Nasser,Male,32.5,,2,0,C
124,Miss. Susan Webber,Female,32.5,E101,2,1,S
125,Mr. Percival Wayland White,Male,54.0,D26,1,0,S
126,Master. Elias Nicola-Yarred,Male,12.0,,3,1,C
128,Mr. Fridtjof Arne Madsen,Male,24.0,,3,1,S
130,Mr. Johan Ekstrom,Male,45.0,,3,0,S
131,Mr. Jozef Drazenoic,Male,33.0,,3,0,C
132,Mr. Domingos Fernandeo Coelho,Male,20.0,,3,0,S
133,Mrs. Alexander A Robins,Female,47.0,,3,0,S
134,Mrs. Leopold Weisz,Female,29.0,,2,1,S
135,Mr. Samuel James Hayden Sobey,Male,25.0,,2,0,S
136,Mr. Emile Richard,Male,23.0,,2,0,C
137,Miss. Helen Monypeny Newsom,Female,19.0,D47,1,1,S
138,Mr. Jacques Heath Futrelle,Male,37.0,C123,1,0,S
139,Mr. Olaf Elon Osen,Male,16.0,,3,0,S
140,Mr. Victor Giglio,Male,24.0,B86,1,0,C
142,Miss. Anna Sofia Nysten,Female,22.0,,3,1,S
143,Mrs. Pekka Pietari Hakkarainen,Female,24.0,,3,1,S
144,Mr. Jeremiah Burke,Male,19.0,,3,0,Q
145,Mr. Edgardo Samuel Andrew,Male,18.0,,2,0,S
146,Mr. Joseph Charles Nicholls,Male,19.0,,2,0,S
147,Mr. August Edvard Andersson,Male,27.0,,3,1,S
148,Miss. Robina Maggie Ford,Female,9.0,,3,0,S
149,Mr. Michel Navratil,Male,36.5,F2,2,0,S
150,Rev. Thomas Roussel Davids Byles,Male,42.0,,2,0,S
151,Rev. Robert James Bateman,Male,51.0,,2,0,S
152,Mrs. Thomas Pears,Female,22.0,C2,1,1,S
153,Mr. Alfonzo Meo,Male,55.5,,3,0,S
154,Mr. Austin Blyler van Billiard,Male,40.5,,3,0,S
156,Mr. Charles Duane Williams,Male,51.0,,1,0,C
157,Miss. Katherine Gilnagh,Female,16.0,,3,1,Q
158,Mr. Harry Corn,Male,30.0,,3,0,S
161,Mr. John Hatfield Cribb,Male,44.0,,3,0,S
162,Mrs. James Watt,Female,40.0,,2,1,S
163,Mr. John Viktor Bengtsson,Male,26.0,,3,0,S
164,Mr. Jovo Calic,Male,17.0,,3,0,S
165,Master. Eino Viljami Panula,Male,1.0,,3,0,S
166,Master. Frank John William Goldsmith,Male,9.0,,3,1,S
168,Mrs. William Skoog,Female,45.0,,3,0,S
170,Mr. Lee Ling,Male,28.0,,3,0,S
171,Mr. Wyckoff Van der hoef,Male,61.0,B19,1,0,S
172,Master. Arthur Rice,Male,4.0,,3,0,Q
173,Miss. Eleanor Ileen Johnson,Female,1.0,,3,1,S
174,Mr. Antti Wilhelm Sivola,Male,21.0,,3,0,S
175,Mr. James Clinch Smith,Male,56.0,A7,1,0,C
176,Mr. Klas Albin Klasen,Male,18.0,,3,0,S
178,Miss. Ann Elizabeth Isham,Female,50.0,C49,1,0,C
179,Mr. Reginald Hale,Male,30.0,,2,0,S
180,Mr. Lionel Leonard,Male,36.0,,3,0,S
183,Master. Clarence Gustaf Hugo Asplund,Male,9.0,,3,0,S
184,Master. Richard F Becker,Male,1.0,F4,2,1,S
185,Miss. Luise Gretchen Kink-Heilmann,Female,4.0,,3,1,S
188,Mr. Charles Hallace Romaine,Male,45.0,,1,1,S
189,Mr. John Bourke,Male,40.0,,3,0,Q
190,Mr. Stjepan Turcin,Male,36.0,,3,0,S
191,Mrs. Pinsky,Female,32.0,,2,1,S
192,Mr. William Carbines,Male,19.0,,2,0,S
193,Miss. Carla Christine Nielsine Andersen-Jensen,Female,19.0,,3,1,S
194,Master. Michel M Navratil,Male,3.0,F2,2,1,S
195,Mrs. James Joseph Brown,Female,44.0,B4,1,1,C
196,Miss. Elise Lurette,Female,58.0,B80,1,1,C
198,Mr. Karl Siegwart Andreas Olsen,Male,42.0,,3,0,S
200,Miss. Henriette Yrois,Female,24.0,,2,0,S
201,Mr. Nestor Cyriel Vande Walle,Male,28.0,,3,0,S
203,Mr. Jakob Alfred Johanson,Male,34.0,,3,0,S
204,Mr. Gerious Youseff,Male,45.5,,3,0,C
205,Mr. Gurshon Cohen,Male,18.0,,3,1,S
206,Miss. Telma Matilda Strom,Female,2.0,G6,3,0,S
207,Mr. Karl Alfred Backstrom,Male,32.0,,3,0,S
208,Mr. Nassef Cassem Albimona,Male,26.0,,3,1,C
209,Miss. Helen Carr,Female,16.0,,3,1,Q
210,Mr. Henry Blank,Male,40.0,A31,1,1,C
211,Mr. Ahmed Ali,Male,24.0,,3,0,S
212,Miss. Clear Annie Cameron,Female,35.0,,2,1,S
213,Mr. John Henry Perkin,Male,22.0,,3,0,S
214,Mr. Hans Kristensen Givard,Male,30.0,,2,0,S
216,Miss. Madeleine Newell,Female,31.0,D36,1,1,C
217,Miss. Eliina Honkanen,Female,27.0,,3,1,S
218,Mr. Sidney Samuel Jacobsohn,Male,42.0,,2,0,S
219,Miss. Albina Bazzani,Female,32.0,D15,1,1,C
220,Mr. Walter Harris,Male,30.0,,2,0,S
221,Mr. Victor Francis Sunderland,Male,16.0,,3,1,S
222,Mr. James H Bracken,Male,27.0,,2,0,S
223,Mr. George Henry Green,Male,51.0,,3,0,S
225,Mr. Frederick Maxfield Hoyt,Male,38.0,C93,1,1,S
226,Mr. Karl Ivar Sven Berglund,Male,22.0,,3,0,S
227,Mr. William John Mellors,Male,19.0,,2,1,S
228,Mr. John Hall Lovell,Male,20.5,,3,0,S
229,Mr. Arne Jonas Fahlstrom,Male,18.0,,2,0,S
231,Mrs. Henry Birkhardt Harris,Female,35.0,C83,1,1,S
232,Mr. Bengt Edvin Larsson,Male,29.0,,3,0,S
233,Mr. Ernst Adolf Sjostedt,Male,59.0,,2,0,S
234,Miss. Lillian Gertrud Asplund,Female,5.0,,3,1,S
235,Mr. Robert William Norman Leyson,Male,24.0,,2,0,S
237,Mr. Stephen Hold,Male,44.0,,2,0,S
238,Miss. Marjorie Collyer,Female,8.0,,2,1,S
239,Mr. Frederick William Pengelly,Male,19.0,,2,0,S
240,Mr. George Henry Hunt,Male,33.0,,2,0,S
243,Mr. Reginald Charles Coleridge,Male,29.0,,2,0,S
244,Mr. Matti Alexanteri Maenpaa,Male,22.0,,3,0,S
245,Mr. Sleiman Attalah,Male,30.0,,3,0,C
246,Dr. William Edward Minahan,Male,44.0,C78,1,0,Q
247,Miss. Agda Thorilda Viktoria Lindahl,Female,25.0,,3,0,S
248,Mrs. William Hamalainen,Female,24.0,,2,1,S
249,Mr. Richard Leonard Beckwith,Male,37.0,D35,1,1,S
250,Rev. Ernest Courtenay Carter,Male,54.0,,2,0,S
252,Mrs. Wilhelm Strom,Female,29.0,G6,3,0,S
253,Mr. William Thomas Stead,Male,62.0,C87,1,0,S
254,Mr. William Arthur Lobb,Male,30.0,,3,0,S
255,Mrs. Viktor Rosblom,Female,41.0,,3,0,S
256,Mrs. Darwis Touma,Female,29.0,,3,1,C
258,Miss. Gladys Cherry,Female,30.0,B77,1,1,S
259,Miss. Anna Ward,Female,35.0,,1,1,C
260,Mrs. Parrish,Female,50.0,,2,1,S
262,Master. Edvin Rojj Felix Asplund,Male,3.0,,3,1,S
263,Mr. Emil Taussig,Male,52.0,E67,1,0,S
264,Mr. William Harrison,Male,40.0,B94,1,0,S
266,Mr. David Reeves,Male,36.0,,2,0,S
267,Mr. Ernesti Arvid Panula,Male,16.0,,3,0,S
268,Mr. Ernst Ulrik Persson,Male,25.0,,3,1,S
269,Mrs. William Thompson Graham,Female,58.0,C125,1,1,S
270,Miss. Amelia Bissette,Female,35.0,C99,1,1,S
272,Mr. William Henry Tornquist,Male,25.0,,3,1,S
273,Mrs. Mellinger,Female,41.0,,2,1,S
274,Mr. Charles H Natsch,Male,37.0,C118,1,0,C
276,Miss. Kornelia Theodosia Andrews,Female,63.0,D7,1,1,S
277,Miss. Augusta Charlotta Lindblom,Female,45.0,,3,0,S
279,Master. Eric Rice,Male,7.0,,3,0,Q
280,Mrs. Stanton Abbott,Female,35.0,,3,1,S
281,Mr. Frank Duane,Male,65.0,,3,0,Q
282,Mr. Nils Johan Goransson Olsson,Male,28.0,,3,0,S
283,Mr. Alfons de Pelsmaeker,Male,16.0,,3,0,S
284,Mr. Edward Arthur Dorking,Male,19.0,,3,1,S
286,Mr. Ivan Stankovic,Male,33.0,,3,0,C
287,Mr. Theodore de Mulder,Male,30.0,,3,1,S
288,Mr. Penko Naidenoff,Male,22.0,,3,0,S
289,Mr. Masabumi Hosono,Male,42.0,,2,1,S
290,Miss. Kate Connolly,Female,22.0,,3,1,Q
291,Miss. Ellen Barber,Female,26.0,,1,1,S
292,Mrs. Dickinson H Bishop,Female,19.0,B49,1,1,C
293,Mr. Rene Jacques Levy,Male,36.0,D,2,0,C
294,Miss. Aloisia Haas,Female,24.0,,3,0,S
295,Mr. Ivan Mineff,Male,24.0,,3,0,S
297,Mr. Mansour Hanna,Male,23.5,,3,0,C
298,Miss. Helen Loraine Allison,Female,2.0,C22 C26,1,0,S
300,Mrs. James Baxter,Female,50.0,B58 B60,1,1,C
303,Mr. William Cahoone Jr Johnson,Male,19.0,,3,0,S
306,Master. Hudson Trevor Allison,Male,0.92,C22 C26,1,1,S
308,Mrs. Victor de Satode Penasco y Castellana,Female,17.0,C65,1,1,C
309,Mr. Samuel Abelson,Male,30.0,,2,0,C
310,Miss. Laura Mabel Francatelli,Female,30.0,E36,1,1,C
311,Miss. Margaret Bechstein Hays,Female,24.0,C54,1,1,C
312,Miss. Emily Borie Ryerson,Female,18.0,B57 B59 B63 B66,1,1,C
313,Mrs. William Lahtinen,Female,26.0,,2,0,S
314,Mr. Ignjac Hendekovic,Male,28.0,,3,0,S
315,Mr. Benjamin Hart,Male,43.0,,2,0,S
316,Miss. Helmina Josefina Nilsson,Female,26.0,,3,1,S
317,Mrs. Sinai Kantor,Female,24.0,,2,1,S
318,Dr. Ernest Moraweck,Male,54.0,,2,0,S
319,Miss. Mary Natalie Wick,Female,31.0,C7,1,1,S
320,Mrs. Frederic Oakley Spedden,Female,40.0,E34,1,1,C
321,Mr. Samuel Dennis,Male,22.0,,3,0,S
322,Mr. Yoto Danoff,Male,27.0,,3,0,S
323,Miss. Hilda Mary Slayter,Female,30.0,,2,1,Q
324,Mrs. Albert Francis Caldwell,Female,22.0,,2,1,S
326,Miss. Marie Grice Young,Female,36.0,C32,1,1,C
327,Mr. Johan Hansen Nysveen,Male,61.0,,3,0,S
328,Mrs. Ball,Female,36.0,D,2,1,S
329,Mrs. Frank John Goldsmith,Female,31.0,,3,1,S
330,Miss. Jean Gertrude Hippach,Female,16.0,B18,1,1,C
332,Mr. Austen Partner,Male,45.5,C124,1,0,S
333,Mr. George Edward Graham,Male,38.0,C91,1,0,S
334,Mr. Leo Edmondus Vander Planke,Male,16.0,,3,0,S
337,Mr. Thomas Clinton Pears,Male,29.0,C2,1,0,S
338,Miss. Elizabeth Margaret Burns,Female,41.0,E40,1,1,C
339,Mr. Karl Edwart Dahl,Male,45.0,,3,1,S
340,Mr. Stephen Weart Blackwell,Male,45.0,T,1,0,S
341,Master. Edmond Roger Navratil,Male,2.0,F2,2,1,S
342,Miss. Alice Elizabeth Fortune,Female,24.0,C23 C25 C27,1,1,S
343,Mr. Erik Gustaf Collander,Male,28.0,,2,0,S
344,Mr. Charles Frederick Waddington Sedgwick,Male,25.0,,2,0,S
345,Mr. Stanley Hubert Fox,Male,36.0,,2,0,S
346,Miss. Amelia Brown,Female,24.0,F33,2,1,S
347,Miss. Marion Elsie Smith,Female,40.0,,2,1,S
349,Master. William Loch Coutts,Male,3.0,,3,1,S
350,Mr. Jovan Dimic,Male,42.0,,3,0,S
351,Mr. Nils Martin Odahl,Male,23.0,,3,0,S
353,Mr. Tannous Elias,Male,15.0,,3,0,C
354,Mr. Josef Arnold-Franchi,Male,25.0,,3,0,S
356,Mr. Leo Peter Vanden Steen,Male,28.0,,3,0,S
357,Miss. Elsie Edith Bowerman,Female,22.0,E33,1,1,S
358,Miss. Annie Clemmer Funk,Female,38.0,,2,0,S
361,Mr. Wilhelm Skoog,Male,40.0,,3,0,S
362,Mr. Sebastiano del Carlo,Male,29.0,,2,0,C
363,Mrs. Barbara,Female,45.0,,3,0,C
364,Mr. Adola Asim,Male,35.0,,3,0,S
366,Mr. Mauritz Nils Martin Adahl,Male,30.0,,3,0,S
367,Mrs. Frank Manley Warren,Female,60.0,D37,1,1,C
370,Mme. Leontine Pauline Aubart,Female,24.0,B35,1,1,C
371,Mr. George Achilles Harder,Male,25.0,E50,1,1,C
372,Mr. Jakob Alfred Wiklund,Male,18.0,,3,0,S
373,Mr. William Thomas Beavan,Male,19.0,,3,0,S
374,Mr. Sante Ringhini,Male,22.0,,1,0,C
375,Miss. Stina Viola Palsson,Female,3.0,,3,0,S
377,Miss. Aurora Adelia Landergren,Female,22.0,,3,1,S
378,Mr. Harry Elkins Widener,Male,27.0,C82,1,0,C
379,Mr. Tannous Betros,Male,20.0,,3,0,C
380,Mr. Karl Gideon Gustafsson,Male,19.0,,3,0,S
381,Miss. Rosalie Bidois,Female,42.0,,1,1,C
382,Miss. Maria Nakid,Female,1.0,,3,1,C
383,Mr. Juho Tikkanen,Male,32.0,,3,0,S
384,Mrs. Alexander Oskar Holverson,Female,35.0,,1,1,S
386,Mr. Charles Henry Davies,Male,18.0,,2,0,S
387,Master. Sidney Leonard Goodwin,Male,1.0,,3,0,S
388,Miss. Kate Buss,Female,36.0,,2,1,S
390,Miss. Bertha Lehmann,Female,17.0,,2,1,C
391,Mr. William Ernest Carter,Male,36.0,B96 B98,1,1,S
392,Mr. Carl Olof Jansson,Male,21.0,,3,1,S
393,Mr. Johan Birger Gustafsson,Male,28.0,,3,0,S
394,Miss. Marjorie Newell,Female,23.0,D36,1,1,C
395,Mrs. Hjalmar Sandstrom,Female,24.0,G6,3,1,S
396,Mr. Erik Johansson,Male,22.0,,3,0,S
397,Miss. Elina Olsson,Female,31.0,,3,0,S
398,Mr. Peter David McKane,Male,46.0,,2,0,S
399,Dr. Alfred Pain,Male,23.0,,2,0,S
400,Mrs. William H Trout,Female,28.0,,2,1,S
401,Mr. Juha Niskanen,Male,39.0,,3,1,S
402,Mr. John Adams,Male,26.0,,3,0,S
403,Miss. Mari Aina Jussila,Female,21.0,,3,0,S
404,Mr. Pekka Pietari Hakkarainen,Male,28.0,,3,0,S
405,Miss. Marija Oreskovic,Female,20.0,,3,0,S
406,Mr. Shadrach Gale,Male,34.0,,2,0,S
407,Mr. Carl/Charles Peter Widegren,Male,51.0,,3,0,S
408,Master. William Rowe Richards,Male,3.0,,2,1,S
409,Mr. Hans Martin Monsen Birkeland,Male,21.0,,3,0,S
413,Miss. Daisy E Minahan,Female,33.0,C78,1,1,Q
415,Mr. Johan Julian Sundman,Male,44.0,,3,1,S
417,Mrs. James Vivian Drew,Female,34.0,,2,1,S
418,Miss. Lyyli Karoliina Silven,Female,18.0,,2,1,S
419,Mr. William John Matthews,Male,30.0,,2,0,S
420,Miss. Catharina Van Impe,Female,10.0,,3,0,S
422,Mr. David Charters,Male,21.0,,3,0,Q
423,Mr. Leo Zimmerman,Male,29.0,,3,0,S
424,Mrs. Ernst Gilbert Danbom,Female,28.0,,3,0,S
425,Mr. Viktor Richard Rosblom,Male,18.0,,3,0,S
427,Mrs. Charles V Clarke,Female,28.0,,2,1,S
428,Miss. Kate Florence Phillips,Female,19.0,,2,1,S
430,Mr. Berk Pickard,Male,32.0,E10,3,1,S
431,Mr. Mauritz Hakan Bjornstrom-Steffansson,Male,28.0,C52,1,1,S
433,Mrs. Charles Alexander Louch,Female,42.0,,2,1,S
434,Mr. Nikolai Erland Kallio,Male,17.0,,3,0,S
435,Mr. William Baird Silvey,Male,50.0,E44,1,0,S
436,Miss. Lucile Polk Carter,Female,14.0,B96 B98,1,1,S
437,Miss. Doolina Margaret Ford,Female,21.0,,3,0,S
438,Mrs. Sidney Richards,Female,24.0,,2,1,S
439,Mr. Mark Fortune,Male,64.0,C23 C25 C27,1,0,S
440,Mr. Johan Henrik Johannesson Kvillner,Male,31.0,,2,0,S
441,Mrs. Benjamin Hart,Female,45.0,,2,1,S
442,Mr. Leon Hampe,Male,20.0,,3,0,S
443,Mr. Johan Emil Petterson,Male,25.0,,3,0,S
444,Ms. Encarnacion Reynaldo,Female,28.0,,2,1,S
446,Master. Washington Dodge,Male,4.0,A34,1,1,S
447,Miss. Madeleine Violet Mellinger,Female,13.0,,2,1,S
448,Mr. Frederic Kimber Seward,Male,34.0,,1,1,S
449,Miss. Marie Catherine Baclini,Female,5.0,,3,1,C
450,Major. Arthur Godfrey Peuchen,Male,52.0,C104,1,1,S
451,Mr. Edwy Arthur West,Male,36.0,,2,0,S
453,Mr. Benjamin Laventall Foreman,Male,30.0,C111,1,0,C
454,Mr. Samuel L Goldenberg,Male,49.0,C92,1,1,C
456,Mr. Ivan Jalsevac,Male,29.0,,3,1,C
457,Mr. Francis Davis Millet,Male,65.0,E38,1,0,S
459,Miss. Ellen Toomey,Female,50.0,,2,1,S
461,Mr. Harry Anderson,Male,48.0,E12,1,1,S
462,Mr. William Morley,Male,34.0,,3,0,S
463,Mr. Arthur H Gee,Male,47.0,E63,1,0,S
464,Mr. Jacob Christian Milling,Male,48.0,,2,0,S
466,Mr. Manuel Estanslas Goncalves,Male,38.0,,3,0,S
468,Mr. John Montgomery Smart,Male,56.0,,1,0,S
470,Miss. Helene Barbara Baclini,Female,0.75,,3,1,C
472,Mr. Luka Cacic,Male,38.0,,3,0,S
473,Mrs. Edwy Arthur West,Female,33.0,,2,1,S
474,Mrs. Amin S Jerwan,Female,23.0,D,2,1,C
475,Miss. Ida Sofia Strandberg,Female,22.0,,3,0,S
477,Mr. Peter Henry Renouf,Male,34.0,,2,0,S
478,Mr. Lewis Richard Braund,Male,29.0,,3,0,S
479,Mr. Nils August Karlsson,Male,22.0,,3,0,S
480,Miss. Hildur E Hirvonen,Female,2.0,,3,1,S
481,Master. Harold Victor Goodwin,Male,9.0,,3,0,S
483,Mr. Richard Henry Rouse,Male,50.0,,3,0,S
484,Mrs. Turkula,Female,63.0,,3,1,S
485,Mr. Dickinson H Bishop,Male,25.0,B49,1,1,C
487,Mrs. Frederick Maxfield Hoyt,Female,35.0,C93,1,1,S
488,Mr. Edward Austin Kent,Male,58.0,B37,1,0,C
489,Mr. Francis William Somerton,Male,30.0,,3,0,S
490,Master. Eden Leslie Coutts,Male,9.0,,3,1,S
492,Mr. Einar Windelov,Male,21.0,,3,0,S
493,Mr. Harry Markland Molson,Male,55.0,C30,1,0,S
494,Mr. Ramon Artagaveytia,Male,71.0,,1,0,C
495,Mr. Edward Roland Stanley,Male,21.0,,3,0,S
497,Miss. Elizabeth Mussey Eustis,Female,54.0,D20,1,1,C
499,Mrs. Hudson J C Allison,Female,25.0,C22 C26,1,0,S
500,Mr. Olof Svensson,Male,24.0,,3,0,S
501,Mr. Petar Calic,Male,17.0,,3,0,S
502,Miss. Mary Canavan,Female,21.0,,3,0,Q
504,Miss. Kristina Sofia Laitinen,Female,37.0,,3,0,S
505,Miss. Roberta Maioni,Female,16.0,B79,1,1,S
506,Mr. Victor de Satode Penasco y Castellana,Male,18.0,C65,1,0,C
507,Mrs. Frederick Charles Quick,Female,33.0,,2,1,S
509,Mr. Henry Margido Olsen,Male,28.0,,3,0,S
510,Mr. Fang Lang,Male,26.0,,3,1,S
511,Mr. Eugene Patrick Daly,Male,29.0,,3,1,Q
513,Mr. James Robert McGough,Male,36.0,E25,1,1,S
514,Mrs. Martin Rothschild,Female,54.0,,1,1,C
515,Mr. Satio Coleff,Male,24.0,,3,0,S
516,Mr. William Anderson Walker,Male,47.0,D46,1,0,S
517,Mrs. Lemore,Female,34.0,F33,2,1,S
519,Mrs. William A Angle,Female,36.0,,2,1,S
520,Mr. Stefo Pavlovic,Male,32.0,,3,0,S
521,Miss. Anne Perreault,Female,30.0,B73,1,1,S
522,Mr. Janko Vovk,Male,22.0,,3,0,S
524,Mrs. Louis Albert Hippach,Female,44.0,B18,1,1,C
526,Mr. James Farrell,Male,40.5,,3,0,Q
527,Miss. Lucy Ridsdale,Female,50.0,,2,1,S
529,Mr. Johan Werner Salonen,Male,39.0,,3,0,S
530,Mr. Richard George Hocking,Male,23.0,,2,0,S
531,Miss. Phyllis May Quick,Female,2.0,,2,1,S
533,Mr. Joseph Jr Elias,Male,17.0,,3,0,C
535,Miss. Marija Cacic,Female,30.0,,3,0,S
536,Miss. Eva Miriam Hart,Female,7.0,,2,1,S
537,Major. Archibald Willingham Butt,Male,45.0,B38,1,0,S
538,Miss. Bertha LeRoy,Female,30.0,,1,1,C
540,Miss. Hedwig Margaritha Frolicher,Female,22.0,B39,1,1,C
541,Miss. Harriet R Crosby,Female,36.0,B22,1,1,S

In [259]:
df[df['Name'].str.contains(r'\b[A-Za-z]\b', regex=True)]

,Name,Sex,Age,Cabin,Pclass,Survived,Embarked
PassengerId,,,,,,,
7,Mr. Timothy J McCarthy,Male,54.0,E46,1,0,S
9,Mrs. Oscar W Johnson,Female,27.0,,3,1,S
21,Mr. Joseph J Fynney,Male,35.0,,2,0,S
31,Don. Manuel E Uruchurtu,Male,40.0,,1,0,C
34,Mr. Edward H Wheadon,Male,66.0,,2,0,S
84,Mr. Francisco M Carrau,Male,28.0,,1,0,S
97,Mr. George B Goldschmidt,Male,71.0,A5,1,0,C
99,Mrs. John T Doling,Female,34.0,,2,1,S
133,Mrs. Alexander A Robins,Female,47.0,,3,0,S
184,Master. Richard F Becker,Male,1.0,F4,2,1,S
194,Master. Michel M Navratil,Male,3.0,F2,2,1,S
222,Mr. James H Bracken,Male,27.0,,2,0,S
274,Mr. Charles H Natsch,Male,37.0,C118,1,0,C
292,Mrs. Dickinson H Bishop,Female,19.0,B49,1,1,C
308,Mrs. Victor de Satode Penasco y Castellana,Female,17.0,C65,1,1,C
400,Mrs. William H Trout,Female,28.0,,2,1,S
413,Miss. Daisy E Minahan,Female,33.0,C78,1,1,Q
427,Mrs. Charles V Clarke,Female,28.0,,2,1,S
454,Mr. Samuel L Goldenberg,Male,49.0,C92,1,1,C
463,Mr. Arthur H Gee,Male,47.0,E63,1,0,S
474,Mrs. Amin S Jerwan,Female,23.0,D,2,1,C
480,Miss. Hildur E Hirvonen,Female,2.0,,3,1,S
485,Mr. Dickinson H Bishop,Male,25.0,B49,1,1,C
499,Mrs. Hudson J C Allison,Female,25.0,C22 C26,1,0,S
506,Mr. Victor de Satode Penasco y Castellana,Male,18.0,C65,1,0,C
519,Mrs. William A Angle,Female,36.0,,2,1,S
541,Miss. Harriet R Crosby,Female,36.0,B22,1,1,S
552,Mr. Percival James R Sharp,Male,27.0,,2,0,S
566,Mr. Alfred J Davies,Male,24.0,,3,0,S
610,Miss. Elizabeth W Shutes,Female,40.0,C125,1,1,S
732,Mr. Houssein G N Hassan,Male,11.0,,3,0,C
738,Mr. Gustave J Lesurer,Male,35.0,B101,1,1,C
766,Mrs. John C Hogeboom,Female,51.0,D11,1,1,S
844,Mr. Peter L Lemberopolous,Male,34.5,,3,0,C
867,Miss. Asuncion Duran y More,Female,27.0,,2,1,C

In [281]:
df

,Name,Sex,Age,Cabin,Pclass,Survived,Embarked
PassengerId,,,,,,,
1,Mr. Owen Harris Braund,Male,22.0,,3,0,S
2,Mrs. John Bradley Cumings,Female,38.0,C85,1,1,C
3,Miss. Laina Heikkinen,Female,26.0,,3,1,S
4,Mrs. Jacques Heath Futrelle,Female,35.0,C123,1,1,S
5,Mr. William Henry Allen,Male,35.0,,3,0,S
7,Mr. Timothy J McCarthy,Male,54.0,E46,1,0,S
8,Master. Gosta Leonard Palsson,Male,2.0,,3,0,S
9,Mrs. Oscar W Johnson,Female,27.0,,3,1,S
10,Mrs. Nicholas Nasser,Female,14.0,,2,1,C
11,Miss. Marguerite Rut Sandstrom,Female,4.0,G6,3,1,S
12,Miss. Elizabeth Bonnell,Female,58.0,C103,1,1,S
13,Mr. William Henry Saundercock,Male,20.0,,3,0,S
14,Mr. Anders Johan Andersson,Male,39.0,,3,0,S
15,Miss. Hulda Amanda Adolfina Vestrom,Female,14.0,,3,0,S
16,Mrs. Hewlett,Female,55.0,,2,1,S
17,Master. Eugene Rice,Male,2.0,,3,0,Q
19,Mrs. Julius Vander Planke,Female,31.0,,3,0,S
21,Mr. Joseph J Fynney,Male,35.0,,2,0,S
22,Mr. Lawrence Beesley,Male,34.0,D56,2,1,S
23,Miss. Anna McGowan,Female,15.0,,3,1,Q
24,Mr. William Thompson Sloper,Male,28.0,A6,1,1,S
25,Miss. Torborg Danira Palsson,Female,8.0,,3,0,S
26,Mrs. Carl Oscar Asplund,Female,38.0,,3,1,S
28,Mr. Charles Alexander Fortune,Male,19.0,C23 C25 C27,1,0,S
31,Don. Manuel E Uruchurtu,Male,40.0,,1,0,C
34,Mr. Edward H Wheadon,Male,66.0,,2,0,S
35,Mr. Edgar Joseph Meyer,Male,28.0,,1,0,C
36,Mr. Alexander Oskar Holverson,Male,42.0,,1,0,S
38,Mr. Ernest Charles Cann,Male,21.0,,3,0,S
39,Miss. Augusta Maria Vander Planke,Female,18.0,,3,0,S
40,Miss. Jamila Nicola-Yarred,Female,14.0,,3,1,C
41,Mrs. Johan Ahlin,Female,40.0,,3,0,S
42,Mrs. William John Robert Turpin,Female,27.0,,2,0,S
44,Miss. Simonne Marie Anne Andree Laroche,Female,3.0,,2,1,C
45,Miss. Margaret Delia Devaney,Female,19.0,,3,1,Q
50,Mrs. Josef Arnold-Franchi,Female,18.0,,3,0,S
51,Master. Juha Niilo Panula,Male,7.0,,3,0,S
52,Mr. Richard Cater Nosworthy,Male,21.0,,3,0,S
53,Mrs. Henry Sleeper Harper,Female,49.0,D33,1,1,C
54,Mrs. Lizzie Faunthorpe,Female,29.0,,2,1,S
55,Mr. Engelhart Cornelius Ostby,Male,65.0,B30,1,0,C
57,Miss. Emily Rugg,Female,21.0,,2,1,S
58,Mr. Mansouer Novel,Male,28.5,,3,0,C
59,Miss. Constance Mirium West,Female,5.0,,2,1,S
60,Master. William Frederick Goodwin,Male,11.0,,3,0,S
61,Mr. Orsen Sirayanian,Male,22.0,,3,0,C
62,Miss. Amelie Icard,Female,38.0,B28,1,1,
63,Mr. Henry Birkhardt Harris,Male,45.0,C83,1,0,S
64,Master. Harald Skoog,Male,4.0,,3,0,S
67,Mrs. Nye,Female,29.0,F33,2,1,S
68,Mr. Ernest James Crease,Male,19.0,,3,0,S
69,Miss. Erna Alexandra Andersson,Female,17.0,,3,1,S
70,Mr. Vincenz Kink,Male,26.0,,3,0,S
71,Mr. Stephen Curnow Jenkin,Male,32.0,,2,0,S
72,Miss. Lillian Amy Goodwin,Female,16.0,,3,0,S
73,Mr. Ambrose Jr Hood,Male,21.0,,2,0,S
74,Mr. Apostolos Chronopoulos,Male,26.0,,3,0,C
75,Mr. Lee Bing,Male,32.0,,3,1,S
76,Mr. Sigurd Hansen Moen,Male,25.0,F G73,3,0,S
79,Master. Alden Gates Caldwell,Male,0.83,,2,1,S
80,Miss. Elizabeth Dowdell,Female,30.0,,3,1,S
81,Mr. Achille Waelens,Male,22.0,,3,0,S
82,Mr. Jan Baptist Sheerlinck,Male,29.0,,3,1,S
84,Mr. Francisco M Carrau,Male,28.0,,1,0,S
85,Miss. Bertha Ilett,Female,17.0,,2,1,S
86,Mrs. Karl Alfred Backstrom,Female,33.0,,3,1,S
87,Mr. William Neal Ford,Male,16.0,,3,0,S
89,Miss. Mabel Helen Fortune,Female,23.0,C23 C25 C27,1,1,S
90,Mr. Francesco Celotti,Male,24.0,,3,0,S
91,Mr. Emil Christmann,Male,29.0,,3,0,S
92,Mr. Paul Edvin Andreasson,Male,20.0,,3,0,S
93,Mr. Herbert Fuller Chaffee,Male,46.0,E31,1,0,S
94,Mr. Bertram Frank Dean,Male,26.0,,3,0,S
95,Mr. Daniel Coxon,Male,59.0,,3,0,S
97,Mr. George B Goldschmidt,Male,71.0,A5,1,0,C
98,Mr. William Bertram Greenfield,Male,23.0,D10 D12,1,1,C
99,Mrs. John T Doling,Female,34.0,,2,1,S
100,Mr. Sinai Kantor,Male,34.0,,2,0,S
101,Miss. Matilda Petranec,Female,28.0,,3,0,S
103,Mr. Richard Frasar White,Male,21.0,D26,1,0,S
104,Mr. Gustaf Joel Johansson,Male,33.0,,3,0,S
105,Mr. Anders Vilhelm Gustafsson,Male,37.0,,3,0,S
106,Mr. Stoytcho Mionoff,Male,28.0,,3,0,S
107,Miss. Anna Kristine Salkjelsvik,Female,21.0,,3,1,S
109,Mr. Tido Rekic,Male,38.0,,3,0,S
111,Mr. Walter Chamberlain Porter,Male,47.0,C110,1,0,S
112,Miss. Hileni Zabour,Female,14.5,,3,0,C
113,Mr. David John Barton,Male,22.0,,3,0,S
114,Miss. Katriina Jussila,Female,20.0,,3,0,S
115,Miss. Malake Attalah,Female,17.0,,3,0,C
116,Mr. Edvard Pekoniemi,Male,21.0,,3,0,S
117,Mr. Patrick Connors,Male,70.5,,3,0,Q
118,Mr. William John Robert Turpin,Male,29.0,,2,0,S
119,Mr. Quigg Edmond Baxter,Male,24.0,B58 B60,1,0,C
120,Miss. Ellis Anna Maria Andersson,Female,2.0,,3,0,S
121,Mr. Stanley George Hickman,Male,21.0,,2,0,S
123,Mr. Nicholas Nasser,Male,32.5,,2,0,C
124,Miss. Susan Webber,Female,32.5,E101,2,1,S
125,Mr. Percival Wayland White,Male,54.0,D26,1,0,S
126,Master. Elias Nicola-Yarred,Male,12.0,,3,1,C
128,Mr. Fridtjof Arne Madsen,Male,24.0,,3,1,S
130,Mr. Johan Ekstrom,Male,45.0,,3,0,S
131,Mr. Jozef Drazenoic,Male,33.0,,3,0,C
132,Mr. Domingos Fernandeo Coelho,Male,20.0,,3,0,S
133,Mrs. Alexander A Robins,Female,47.0,,3,0,S
134,Mrs. Leopold Weisz,Female,29.0,,2,1,S
135,Mr. Samuel James Hayden Sobey,Male,25.0,,2,0,S
136,Mr. Emile Richard,Male,23.0,,2,0,C
137,Miss. Helen Monypeny Newsom,Female,19.0,D47,1,1,S
138,Mr. Jacques Heath Futrelle,Male,37.0,C123,1,0,S
139,Mr. Olaf Elon Osen,Male,16.0,,3,0,S
140,Mr. Victor Giglio,Male,24.0,B86,1,0,C
142,Miss. Anna Sofia Nysten,Female,22.0,,3,1,S
143,Mrs. Pekka Pietari Hakkarainen,Female,24.0,,3,1,S
144,Mr. Jeremiah Burke,Male,19.0,,3,0,Q
145,Mr. Edgardo Samuel Andrew,Male,18.0,,2,0,S
146,Mr. Joseph Charles Nicholls,Male,19.0,,2,0,S
147,Mr. August Edvard Andersson,Male,27.0,,3,1,S
148,Miss. Robina Maggie Ford,Female,9.0,,3,0,S
149,Mr. Michel Navratil,Male,36.5,F2,2,0,S
150,Rev. Thomas Roussel Davids Byles,Male,42.0,,2,0,S
151,Rev. Robert James Bateman,Male,51.0,,2,0,S
152,Mrs. Thomas Pears,Female,22.0,C2,1,1,S
153,Mr. Alfonzo Meo,Male,55.5,,3,0,S
154,Mr. Austin Blyler van Billiard,Male,40.5,,3,0,S
156,Mr. Charles Duane Williams,Male,51.0,,1,0,C
157,Miss. Katherine Gilnagh,Female,16.0,,3,1,Q
158,Mr. Harry Corn,Male,30.0,,3,0,S
161,Mr. John Hatfield Cribb,Male,44.0,,3,0,S
162,Mrs. James Watt,Female,40.0,,2,1,S
163,Mr. John Viktor Bengtsson,Male,26.0,,3,0,S
164,Mr. Jovo Calic,Male,17.0,,3,0,S
165,Master. Eino Viljami Panula,Male,1.0,,3,0,S
166,Master. Frank John William Goldsmith,Male,9.0,,3,1,S
168,Mrs. William Skoog,Female,45.0,,3,0,S
170,Mr. Lee Ling,Male,28.0,,3,0,S
171,Mr. Wyckoff Van der hoef,Male,61.0,B19,1,0,S
172,Master. Arthur Rice,Male,4.0,,3,0,Q
173,Miss. Eleanor Ileen Johnson,Female,1.0,,3,1,S
174,Mr. Antti Wilhelm Sivola,Male,21.0,,3,0,S
175,Mr. James Clinch Smith,Male,56.0,A7,1,0,C
176,Mr. Klas Albin Klasen,Male,18.0,,3,0,S
178,Miss. Ann Elizabeth Isham,Female,50.0,C49,1,0,C
179,Mr. Reginald Hale,Male,30.0,,2,0,S
180,Mr. Lionel Leonard,Male,36.0,,3,0,S
183,Master. Clarence Gustaf Hugo Asplund,Male,9.0,,3,0,S
184,Master. Richard F Becker,Male,1.0,F4,2,1,S
185,Miss. Luise Gretchen Kink-Heilmann,Female,4.0,,3,1,S
188,Mr. Charles Hallace Romaine,Male,45.0,,1,1,S
189,Mr. John Bourke,Male,40.0,,3,0,Q
190,Mr. Stjepan Turcin,Male,36.0,,3,0,S
191,Mrs. Pinsky,Female,32.0,,2,1,S
192,Mr. William Carbines,Male,19.0,,2,0,S
193,Miss. Carla Christine Nielsine Andersen-Jensen,Female,19.0,,3,1,S
194,Master. Michel M Navratil,Male,3.0,F2,2,1,S
195,Mrs. James Joseph Brown,Female,44.0,B4,1,1,C
196,Miss. Elise Lurette,Female,58.0,B80,1,1,C
198,Mr. Karl Siegwart Andreas Olsen,Male,42.0,,3,0,S
200,Miss. Henriette Yrois,Female,24.0,,2,0,S
201,Mr. Nestor Cyriel Vande Walle,Male,28.0,,3,0,S
203,Mr. Jakob Alfred Johanson,Male,34.0,,3,0,S
204,Mr. Gerious Youseff,Male,45.5,,3,0,C
205,Mr. Gurshon Cohen,Male,18.0,,3,1,S
206,Miss. Telma Matilda Strom,Female,2.0,G6,3,0,S
207,Mr. Karl Alfred Backstrom,Male,32.0,,3,0,S
208,Mr. Nassef Cassem Albimona,Male,26.0,,3,1,C
209,Miss. Helen Carr,Female,16.0,,3,1,Q
210,Mr. Henry Blank,Male,40.0,A31,1,1,C
211,Mr. Ahmed Ali,Male,24.0,,3,0,S
212,Miss. Clear Annie Cameron,Female,35.0,,2,1,S
213,Mr. John Henry Perkin,Male,22.0,,3,0,S
214,Mr. Hans Kristensen Givard,Male,30.0,,2,0,S
216,Miss. Madeleine Newell,Female,31.0,D36,1,1,C
217,Miss. Eliina Honkanen,Female,27.0,,3,1,S
218,Mr. Sidney Samuel Jacobsohn,Male,42.0,,2,0,S
219,Miss. Albina Bazzani,Female,32.0,D15,1,1,C
220,Mr. Walter Harris,Male,30.0,,2,0,S
221,Mr. Victor Francis Sunderland,Male,16.0,,3,1,S
222,Mr. James H Bracken,Male,27.0,,2,0,S
223,Mr. George Henry Green,Male,51.0,,3,0,S
225,Mr. Frederick Maxfield Hoyt,Male,38.0,C93,1,1,S
226,Mr. Karl Ivar Sven Berglund,Male,22.0,,3,0,S
227,Mr. William John Mellors,Male,19.0,,2,1,S
228,Mr. John Hall Lovell,Male,20.5,,3,0,S
229,Mr. Arne Jonas Fahlstrom,Male,18.0,,2,0,S
231,Mrs. Henry Birkhardt Harris,Female,35.0,C83,1,1,S
232,Mr. Bengt Edvin Larsson,Male,29.0,,3,0,S
233,Mr. Ernst Adolf Sjostedt,Male,59.0,,2,0,S
234,Miss. Lillian Gertrud Asplund,Female,5.0,,3,1,S
235,Mr. Robert William Norman Leyson,Male,24.0,,2,0,S
237,Mr. Stephen Hold,Male,44.0,,2,0,S
238,Miss. Marjorie Collyer,Female,8.0,,2,1,S
239,Mr. Frederick William Pengelly,Male,19.0,,2,0,S
240,Mr. George Henry Hunt,Male,33.0,,2,0,S
243,Mr. Reginald Charles Coleridge,Male,29.0,,2,0,S
244,Mr. Matti Alexanteri Maenpaa,Male,22.0,,3,0,S
245,Mr. Sleiman Attalah,Male,30.0,,3,0,C
246,Dr. William Edward Minahan,Male,44.0,C78,1,0,Q
247,Miss. Agda Thorilda Viktoria Lindahl,Female,25.0,,3,0,S
248,Mrs. William Hamalainen,Female,24.0,,2,1,S
249,Mr. Richard Leonard Beckwith,Male,37.0,D35,1,1,S
250,Rev. Ernest Courtenay Carter,Male,54.0,,2,0,S
252,Mrs. Wilhelm Strom,Female,29.0,G6,3,0,S
253,Mr. William Thomas Stead,Male,62.0,C87,1,0,S
254,Mr. William Arthur Lobb,Male,30.0,,3,0,S
255,Mrs. Viktor Rosblom,Female,41.0,,3,0,S
256,Mrs. Darwis Touma,Female,29.0,,3,1,C
258,Miss. Gladys Cherry,Female,30.0,B77,1,1,S
259,Miss. Anna Ward,Female,35.0,,1,1,C
260,Mrs. Parrish,Female,50.0,,2,1,S
262,Master. Edvin Rojj Felix Asplund,Male,3.0,,3,1,S
263,Mr. Emil Taussig,Male,52.0,E67,1,0,S
264,Mr. William Harrison,Male,40.0,B94,1,0,S
266,Mr. David Reeves,Male,36.0,,2,0,S
267,Mr. Ernesti Arvid Panula,Male,16.0,,3,0,S
268,Mr. Ernst Ulrik Persson,Male,25.0,,3,1,S
269,Mrs. William Thompson Graham,Female,58.0,C125,1,1,S
270,Miss. Amelia Bissette,Female,35.0,C99,1,1,S
272,Mr. William Henry Tornquist,Male,25.0,,3,1,S
273,Mrs. Mellinger,Female,41.0,,2,1,S
274,Mr. Charles H Natsch,Male,37.0,C118,1,0,C
276,Miss. Kornelia Theodosia Andrews,Female,63.0,D7,1,1,S
277,Miss. Augusta Charlotta Lindblom,Female,45.0,,3,0,S
279,Master. Eric Rice,Male,7.0,,3,0,Q
280,Mrs. Stanton Abbott,Female,35.0,,3,1,S
281,Mr. Frank Duane,Male,65.0,,3,0,Q
282,Mr. Nils Johan Goransson Olsson,Male,28.0,,3,0,S
283,Mr. Alfons de Pelsmaeker,Male,16.0,,3,0,S
284,Mr. Edward Arthur Dorking,Male,19.0,,3,1,S
286,Mr. Ivan Stankovic,Male,33.0,,3,0,C
287,Mr. Theodore de Mulder,Male,30.0,,3,1,S
288,Mr. Penko Naidenoff,Male,22.0,,3,0,S
289,Mr. Masabumi Hosono,Male,42.0,,2,1,S
290,Miss. Kate Connolly,Female,22.0,,3,1,Q
291,Miss. Ellen Barber,Female,26.0,,1,1,S
292,Mrs. Dickinson H Bishop,Female,19.0,B49,1,1,C
293,Mr. Rene Jacques Levy,Male,36.0,D,2,0,C
294,Miss. Aloisia Haas,Female,24.0,,3,0,S
295,Mr. Ivan Mineff,Male,24.0,,3,0,S
297,Mr. Mansour Hanna,Male,23.5,,3,0,C
298,Miss. Helen Loraine Allison,Female,2.0,C22 C26,1,0,S
300,Mrs. James Baxter,Female,50.0,B58 B60,1,1,C
303,Mr. William Cahoone Jr Johnson,Male,19.0,,3,0,S
306,Master. Hudson Trevor Allison,Male,0.92,C22 C26,1,1,S
308,Mrs. Victor de Satode Penasco y Castellana,Female,17.0,C65,1,1,C
309,Mr. Samuel Abelson,Male,30.0,,2,0,C
310,Miss. Laura Mabel Francatelli,Female,30.0,E36,1,1,C
311,Miss. Margaret Bechstein Hays,Female,24.0,C54,1,1,C
312,Miss. Emily Borie Ryerson,Female,18.0,B57 B59 B63 B66,1,1,C
313,Mrs. William Lahtinen,Female,26.0,,2,0,S
314,Mr. Ignjac Hendekovic,Male,28.0,,3,0,S
315,Mr. Benjamin Hart,Male,43.0,,2,0,S
316,Miss. Helmina Josefina Nilsson,Female,26.0,,3,1,S
317,Mrs. Sinai Kantor,Female,24.0,,2,1,S
318,Dr. Ernest Moraweck,Male,54.0,,2,0,S
319,Miss. Mary Natalie Wick,Female,31.0,C7,1,1,S
320,Mrs. Frederic Oakley Spedden,Female,40.0,E34,1,1,C
321,Mr. Samuel Dennis,Male,22.0,,3,0,S
322,Mr. Yoto Danoff,Male,27.0,,3,0,S
323,Miss. Hilda Mary Slayter,Female,30.0,,2,1,Q
324,Mrs. Albert Francis Caldwell,Female,22.0,,2,1,S
326,Miss. Marie Grice Young,Female,36.0,C32,1,1,C
327,Mr. Johan Hansen Nysveen,Male,61.0,,3,0,S
328,Mrs. Ball,Female,36.0,D,2,1,S
329,Mrs. Frank John Goldsmith,Female,31.0,,3,1,S
330,Miss. Jean Gertrude Hippach,Female,16.0,B18,1,1,C
332,Mr. Austen Partner,Male,45.5,C124,1,0,S
333,Mr. George Edward Graham,Male,38.0,C91,1,0,S
334,Mr. Leo Edmondus Vander Planke,Male,16.0,,3,0,S
337,Mr. Thomas Clinton Pears,Male,29.0,C2,1,0,S
338,Miss. Elizabeth Margaret Burns,Female,41.0,E40,1,1,C
339,Mr. Karl Edwart Dahl,Male,45.0,,3,1,S
340,Mr. Stephen Weart Blackwell,Male,45.0,T,1,0,S
341,Master. Edmond Roger Navratil,Male,2.0,F2,2,1,S
342,Miss. Alice Elizabeth Fortune,Female,24.0,C23 C25 C27,1,1,S
343,Mr. Erik Gustaf Collander,Male,28.0,,2,0,S
344,Mr. Charles Frederick Waddington Sedgwick,Male,25.0,,2,0,S
345,Mr. Stanley Hubert Fox,Male,36.0,,2,0,S
346,Miss. Amelia Brown,Female,24.0,F33,2,1,S
347,Miss. Marion Elsie Smith,Female,40.0,,2,1,S
349,Master. William Loch Coutts,Male,3.0,,3,1,S
350,Mr. Jovan Dimic,Male,42.0,,3,0,S
351,Mr. Nils Martin Odahl,Male,23.0,,3,0,S
353,Mr. Tannous Elias,Male,15.0,,3,0,C
354,Mr. Josef Arnold-Franchi,Male,25.0,,3,0,S
356,Mr. Leo Peter Vanden Steen,Male,28.0,,3,0,S
357,Miss. Elsie Edith Bowerman,Female,22.0,E33,1,1,S
358,Miss. Annie Clemmer Funk,Female,38.0,,2,0,S
361,Mr. Wilhelm Skoog,Male,40.0,,3,0,S
362,Mr. Sebastiano del Carlo,Male,29.0,,2,0,C
363,Mrs. Barbara,Female,45.0,,3,0,C
364,Mr. Adola Asim,Male,35.0,,3,0,S
366,Mr. Mauritz Nils Martin Adahl,Male,30.0,,3,0,S
367,Mrs. Frank Manley Warren,Female,60.0,D37,1,1,C
370,Mme. Leontine Pauline Aubart,Female,24.0,B35,1,1,C
371,Mr. George Achilles Harder,Male,25.0,E50,1,1,C
372,Mr. Jakob Alfred Wiklund,Male,18.0,,3,0,S
373,Mr. William Thomas Beavan,Male,19.0,,3,0,S
374,Mr. Sante Ringhini,Male,22.0,,1,0,C
375,Miss. Stina Viola Palsson,Female,3.0,,3,0,S
377,Miss. Aurora Adelia Landergren,Female,22.0,,3,1,S
378,Mr. Harry Elkins Widener,Male,27.0,C82,1,0,C
379,Mr. Tannous Betros,Male,20.0,,3,0,C
380,Mr. Karl Gideon Gustafsson,Male,19.0,,3,0,S
381,Miss. Rosalie Bidois,Female,42.0,,1,1,C
382,Miss. Maria Nakid,Female,1.0,,3,1,C
383,Mr. Juho Tikkanen,Male,32.0,,3,0,S
384,Mrs. Alexander Oskar Holverson,Female,35.0,,1,1,S
386,Mr. Charles Henry Davies,Male,18.0,,2,0,S
387,Master. Sidney Leonard Goodwin,Male,1.0,,3,0,S
388,Miss. Kate Buss,Female,36.0,,2,1,S
390,Miss. Bertha Lehmann,Female,17.0,,2,1,C
391,Mr. William Ernest Carter,Male,36.0,B96 B98,1,1,S
392,Mr. Carl Olof Jansson,Male,21.0,,3,1,S
393,Mr. Johan Birger Gustafsson,Male,28.0,,3,0,S
394,Miss. Marjorie Newell,Female,23.0,D36,1,1,C
395,Mrs. Hjalmar Sandstrom,Female,24.0,G6,3,1,S
396,Mr. Erik Johansson,Male,22.0,,3,0,S
397,Miss. Elina Olsson,Female,31.0,,3,0,S
398,Mr. Peter David McKane,Male,46.0,,2,0,S
399,Dr. Alfred Pain,Male,23.0,,2,0,S
400,Mrs. William H Trout,Female,28.0,,2,1,S
401,Mr. Juha Niskanen,Male,39.0,,3,1,S
402,Mr. John Adams,Male,26.0,,3,0,S
403,Miss. Mari Aina Jussila,Female,21.0,,3,0,S
404,Mr. Pekka Pietari Hakkarainen,Male,28.0,,3,0,S
405,Miss. Marija Oreskovic,Female,20.0,,3,0,S
406,Mr. Shadrach Gale,Male,34.0,,2,0,S
407,Mr. Carl/Charles Peter Widegren,Male,51.0,,3,0,S
408,Master. William Rowe Richards,Male,3.0,,2,1,S
409,Mr. Hans Martin Monsen Birkeland,Male,21.0,,3,0,S
413,Miss. Daisy E Minahan,Female,33.0,C78,1,1,Q
415,Mr. Johan Julian Sundman,Male,44.0,,3,1,S
417,Mrs. James Vivian Drew,Female,34.0,,2,1,S
418,Miss. Lyyli Karoliina Silven,Female,18.0,,2,1,S
419,Mr. William John Matthews,Male,30.0,,2,0,S
420,Miss. Catharina Van Impe,Female,10.0,,3,0,S
422,Mr. David Charters,Male,21.0,,3,0,Q
423,Mr. Leo Zimmerman,Male,29.0,,3,0,S
424,Mrs. Ernst Gilbert Danbom,Female,28.0,,3,0,S
425,Mr. Viktor Richard Rosblom,Male,18.0,,3,0,S
427,Mrs. Charles V Clarke,Female,28.0,,2,1,S
428,Miss. Kate Florence Phillips,Female,19.0,,2,1,S
430,Mr. Berk Pickard,Male,32.0,E10,3,1,S
431,Mr. Mauritz Hakan Bjornstrom-Steffansson,Male,28.0,C52,1,1,S
433,Mrs. Charles Alexander Louch,Female,42.0,,2,1,S
434,Mr. Nikolai Erland Kallio,Male,17.0,,3,0,S
435,Mr. William Baird Silvey,Male,50.0,E44,1,0,S
436,Miss. Lucile Polk Carter,Female,14.0,B96 B98,1,1,S
437,Miss. Doolina Margaret Ford,Female,21.0,,3,0,S
438,Mrs. Sidney Richards,Female,24.0,,2,1,S
439,Mr. Mark Fortune,Male,64.0,C23 C25 C27,1,0,S
440,Mr. Johan Henrik Johannesson Kvillner,Male,31.0,,2,0,S
441,Mrs. Benjamin Hart,Female,45.0,,2,1,S
442,Mr. Leon Hampe,Male,20.0,,3,0,S
443,Mr. Johan Emil Petterson,Male,25.0,,3,0,S
444,Ms. Encarnacion Reynaldo,Female,28.0,,2,1,S
446,Master. Washington Dodge,Male,4.0,A34,1,1,S
447,Miss. Madeleine Violet Mellinger,Female,13.0,,2,1,S
448,Mr. Frederic Kimber Seward,Male,34.0,,1,1,S
449,Miss. Marie Catherine Baclini,Female,5.0,,3,1,C
450,Major. Arthur Godfrey Peuchen,Male,52.0,C104,1,1,S
451,Mr. Edwy Arthur West,Male,36.0,,2,0,S
453,Mr. Benjamin Laventall Foreman,Male,30.0,C111,1,0,C
454,Mr. Samuel L Goldenberg,Male,49.0,C92,1,1,C
456,Mr. Ivan Jalsevac,Male,29.0,,3,1,C
457,Mr. Francis Davis Millet,Male,65.0,E38,1,0,S
459,Miss. Ellen Toomey,Female,50.0,,2,1,S
461,Mr. Harry Anderson,Male,48.0,E12,1,1,S
462,Mr. William Morley,Male,34.0,,3,0,S
463,Mr. Arthur H Gee,Male,47.0,E63,1,0,S
464,Mr. Jacob Christian Milling,Male,48.0,,2,0,S
466,Mr. Manuel Estanslas Goncalves,Male,38.0,,3,0,S
468,Mr. John Montgomery Smart,Male,56.0,,1,0,S
470,Miss. Helene Barbara Baclini,Female,0.75,,3,1,C
472,Mr. Luka Cacic,Male,38.0,,3,0,S
473,Mrs. Edwy Arthur West,Female,33.0,,2,1,S
474,Mrs. Amin S Jerwan,Female,23.0,D,2,1,C
475,Miss. Ida Sofia Strandberg,Female,22.0,,3,0,S
477,Mr. Peter Henry Renouf,Male,34.0,,2,0,S
478,Mr. Lewis Richard Braund,Male,29.0,,3,0,S
479,Mr. Nils August Karlsson,Male,22.0,,3,0,S
480,Miss. Hildur E Hirvonen,Female,2.0,,3,1,S
481,Master. Harold Victor Goodwin,Male,9.0,,3,0,S
483,Mr. Richard Henry Rouse,Male,50.0,,3,0,S
484,Mrs. Turkula,Female,63.0,,3,1,S
485,Mr. Dickinson H Bishop,Male,25.0,B49,1,1,C
487,Mrs. Frederick Maxfield Hoyt,Female,35.0,C93,1,1,S
488,Mr. Edward Austin Kent,Male,58.0,B37,1,0,C
489,Mr. Francis William Somerton,Male,30.0,,3,0,S
490,Master. Eden Leslie Coutts,Male,9.0,,3,1,S
492,Mr. Einar Windelov,Male,21.0,,3,0,S
493,Mr. Harry Markland Molson,Male,55.0,C30,1,0,S
494,Mr. Ramon Artagaveytia,Male,71.0,,1,0,C
495,Mr. Edward Roland Stanley,Male,21.0,,3,0,S
497,Miss. Elizabeth Mussey Eustis,Female,54.0,D20,1,1,C
499,Mrs. Hudson J C Allison,Female,25.0,C22 C26,1,0,S
500,Mr. Olof Svensson,Male,24.0,,3,0,S
501,Mr. Petar Calic,Male,17.0,,3,0,S
502,Miss. Mary Canavan,Female,21.0,,3,0,Q
504,Miss. Kristina Sofia Laitinen,Female,37.0,,3,0,S
505,Miss. Roberta Maioni,Female,16.0,B79,1,1,S
506,Mr. Victor de Satode Penasco y Castellana,Male,18.0,C65,1,0,C
507,Mrs. Frederick Charles Quick,Female,33.0,,2,1,S
509,Mr. Henry Margido Olsen,Male,28.0,,3,0,S
510,Mr. Fang Lang,Male,26.0,,3,1,S
511,Mr. Eugene Patrick Daly,Male,29.0,,3,1,Q
513,Mr. James Robert McGough,Male,36.0,E25,1,1,S
514,Mrs. Martin Rothschild,Female,54.0,,1,1,C
515,Mr. Satio Coleff,Male,24.0,,3,0,S
516,Mr. William Anderson Walker,Male,47.0,D46,1,0,S
517,Mrs. Lemore,Female,34.0,F33,2,1,S
519,Mrs. William A Angle,Female,36.0,,2,1,S
520,Mr. Stefo Pavlovic,Male,32.0,,3,0,S
521,Miss. Anne Perreault,Female,30.0,B73,1,1,S
522,Mr. Janko Vovk,Male,22.0,,3,0,S
524,Mrs. Louis Albert Hippach,Female,44.0,B18,1,1,C
526,Mr. James Farrell,Male,40.5,,3,0,Q
527,Miss. Lucy Ridsdale,Female,50.0,,2,1,S
529,Mr. Johan Werner Salonen,Male,39.0,,3,0,S
530,Mr. Richard George Hocking,Male,23.0,,2,0,S
531,Miss. Phyllis May Quick,Female,2.0,,2,1,S
533,Mr. Joseph Jr Elias,Male,17.0,,3,0,C
535,Miss. Marija Cacic,Female,30.0,,3,0,S
536,Miss. Eva Miriam Hart,Female,7.0,,2,1,S
537,Major. Archibald Willingham Butt,Male,45.0,B38,1,0,S
538,Miss. Bertha LeRoy,Female,30.0,,1,1,C
540,Miss. Hedwig Margaritha Frolicher,Female,22.0,B39,1,1,C
541,Miss. Harriet R Crosby,Female,36.0,B22,1,1,S